version: "3"
services:
  drdplus:
    build: .
    environment:
      PHP_IDE_CONFIG: "serverName=drdplus.loc"
      PROJECT_ENVIRONMENT: "dev"
      XDEBUG_CONFIG: "client_host=172.17.0.1 client_port=9003 remote_log=/tmp/xdebug.log"
      # XDEBUG_TRIGGER: "yes" # to start XDebug for EVERY request (use `export XDEBUG_TRIGGER: "yes"` to enable it in CLI and `unset XDEBUG_TRIGGER` to disable for CLI again - in browser use same-named variable in GET, POST or COOKIE, or legacy named via some browser extension)
      COMPOSER_AUTH: '{"github-oauth":{"github.com":""}}' # Go to https://github.com/settings/tokens to generate new (read only) access token to let Github pair your requests to your account and to raise the cap of allowed requests (during Composer Github-related actions like install, update, require etc)
    volumes:
      - ./www:/var/www:delegated
      - ./.docker/etc/caddy:/etc/caddy:delegated
      - ~/.cache/composer:/home/www-data/.composer
      - ./.docker/entrypoint.sh:/entrypoint.sh:delegated
      - ./.docker/init-user-www-data.sh:/init-user-www-data.sh:delegated
    entrypoint:
      - sh
      - -c
      - /bin/bash /entrypoint.sh
    networks:
      - default
      - proxy
    restart: "no"

networks:
  proxy:
    external:
      name: docker-www
